### ISSUE TITLE
Fixing test errors (time)

### ISSUE THREAD

**Issue by SurfingNerd** [DMDcoin/hbbft-posdao-contracts#12]
Fixing test errors introduced by switching to time beased epochs instead of blockbased epochs in an AURA.

**Comment by SurfingNerd** [comment]
25 passing (5m)
  23 failing

  1) Contract: BlockRewardHbbft
       reward()
         network started:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Invalid number of parameters for "initialize". Got 9 expected 8!'
  

  2) Contract: BlockRewardHbbft
       reward()
         staking epoch #0 finished:
     TypeError: Cannot read property 'call' of undefined
      at Context.it (test/BlockRewardHbbft.js:128:80)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  3) Contract: BlockRewardHbbft
       reward()
         staking epoch #1 started:

      AssertionError: expected '0' to equal '1'
      + expected - actual

      -0
      +1
      
      at Context.it (test/BlockRewardHbbft.js:150:68)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  4) Contract: BlockRewardHbbft
       reward()
         validators and their delegators place stakes during the epoch #1:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Returned error: VM Exception while processing transaction: revert'
  

  5) Contract: BlockRewardHbbft
       reward()
         staking epoch #1 finished:

      AssertionError: expected '0' to equal '1'
      + expected - actual

      -0
      +1
      
      at Context.it (test/BlockRewardHbbft.js:181:40)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  6) Contract: StakingHbbft
       addPool()
         "before each" hook for "should set the corresponding public keys":
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Invalid number of parameters for "initialize". Got 9 expected 8!'
  

  7) Contract: StakingHbbft
       contract balance
         "before each" hook for "cannot be increased by sending native coins":
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Invalid number of parameters for "initialize". Got 9 expected 8!'
  

  8) Contract: StakingHbbft
       claimReward()
         "before each" hook for "reward tries to be withdrawn before first stake":
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Invalid number of parameters for "initialize". Got 9 expected 8!'
  

  9) Contract: StakingHbbft
       initialize()
         should initialize successfully:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Invalid number of parameters for "initialize". Got 9 expected 8!'
  

  10) Contract: StakingHbbft
       initialize()
         should fail if ValidatorSet contract address is zero:

      AssertionError: expected promise to be rejected with an error including 'ValidatorSet can\'t be 0' but got 'Invalid number of parameters for "initialize". Got 9 expected 8!'
      + expected - actual

      -Invalid number of parameters for "initialize". Got 9 expected 8!
      +ValidatorSet can't be 0
      
  

  11) Contract: StakingHbbft
       initialize()
         should fail if delegatorMinStake is zero:

      AssertionError: expected promise to be rejected with an error including 'DelegatorMinStake is 0' but got 'Invalid number of parameters for "initialize". Got 9 expected 8!'
      + expected - actual

      -Invalid number of parameters for "initialize". Got 9 expected 8!
      +DelegatorMinStake is 0
      
  

  12) Contract: StakingHbbft
       initialize()
         should fail if candidateMinStake is zero:

      AssertionError: expected promise to be rejected with an error including 'CandidateMinStake is 0' but got 'Invalid number of parameters for "initialize". Got 9 expected 8!'
      + expected - actual

      -Invalid number of parameters for "initialize". Got 9 expected 8!
      +CandidateMinStake is 0
      
  

  13) Contract: StakingHbbft
       initialize()
         should fail if already initialized:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Invalid number of parameters for "initialize". Got 9 expected 8!'
  

  14) Contract: StakingHbbft
       initialize()
         should fail if stakingEpochDuration is 0:

      AssertionError: expected promise to be rejected with an error including 'FixedEpochDuration is 0' but got 'Invalid number of parameters for "initialize". Got 9 expected 8!'
      + expected - actual

      -Invalid number of parameters for "initialize". Got 9 expected 8!
      +FixedEpochDuration is 0
      
  

  15) Contract: StakingHbbft
       initialize()
         should fail if stakingstakingEpochStartBlockWithdrawDisallowPeriod is 0:

      AssertionError: expected promise to be rejected with an error including 'WithdrawDisallowPeriod is 0' but got 'Invalid number of parameters for "initialize". Got 9 expected 8!'
      + expected - actual

      -Invalid number of parameters for "initialize". Got 9 expected 8!
      +WithdrawDisallowPeriod is 0
      
  

  16) Contract: StakingHbbft
       initialize()
         should fail if stakingWithdrawDisallowPeriod >= stakingEpochDuration:

      AssertionError: expected promise to be rejected with an error including 'FixedEpochDuration must be longer than withdrawDisallowPeriod' but got 'Invalid number of parameters for "initialize". Got 9 expected 8!'
      + expected - actual

      -Invalid number of parameters for "initialize". Got 9 expected 8!
      +FixedEpochDuration must be longer than withdrawDisallowPeriod
      
  

  17) Contract: StakingHbbft
       initialize()
         should fail if some staking address is 0:

      AssertionError: expected promise to be rejected with an error including 'InitialStakingAddresses can\'t be 0' but got 'Invalid number of parameters for "initialize". Got 9 expected 8!'
      + expected - actual

      -Invalid number of parameters for "initialize". Got 9 expected 8!
      +InitialStakingAddresses can't be 0
      
  

  18) Contract: StakingHbbft
       moveStake()
         "before each" hook for "should move entire stake":
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Invalid number of parameters for "initialize". Got 9 expected 8!'
  

  19) Contract: StakingHbbft
       stake()
         "before each" hook for "should be zero initially":
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Invalid number of parameters for "initialize". Got 9 expected 8!'
  

  20) Contract: StakingHbbft
       removePool()
         "before each" hook for "should remove a pool":
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Invalid number of parameters for "initialize". Got 9 expected 8!'
  

  21) Contract: StakingHbbft
       removeMyPool()
         "before each" hook for "should fail for zero gas price":
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Invalid number of parameters for "initialize". Got 9 expected 8!'
  

  22) Contract: StakingHbbft
       withdraw()
         "before each" hook for "should withdraw a stake":
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Invalid number of parameters for "initialize". Got 9 expected 8!'
  

  23) Contract: ValidatorSetHbbft
       newValidatorSet()
         "before each" hook for "can only be called by BlockReward contract":
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Invalid number of parameters for "initialize". Got 9 expected 8!'

**Comment by SurfingNerd** [comment]
27 passing (8m)
node_modules/mocha/lib/reporters/base.js:349
  18 failing

**Comment by SurfingNerd** [comment]
Removed Block Wise Rewards.
function setBlocksCreated(uint256 _stakingEpoch, uint256 _blocks)
function clearBlocksCreated() external;
Checkin: ecb98b9f03b68d64c0c3d8b1a8965c3613e3f6d7

  30 passing (5m)
  18 failing

  1) Contract: StakingHbbft
       addPool()
         "before each" hook for "should set the corresponding public keys":
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Invalid number of parameters for "initialize". Got 9 expected 8!'
  

  2) Contract: StakingHbbft
       contract balance
         "before each" hook for "cannot be increased by sending native coins":
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Invalid number of parameters for "initialize". Got 9 expected 8!'
  

  3) Contract: StakingHbbft
       claimReward()
         "before each" hook for "reward tries to be withdrawn before first stake":
     ReferenceError: maxBlockReward is not defined
      at Context.beforeEach (test/StakingHbbft.js:320:9)

  4) Contract: StakingHbbft
       initialize()
         should initialize successfully:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Invalid number of parameters for "initialize". Got 9 expected 8!'
  

  5) Contract: StakingHbbft
       initialize()
         should fail if ValidatorSet contract address is zero:

      AssertionError: expected promise to be rejected with an error including 'ValidatorSet can\'t be 0' but got 'Invalid number of parameters for "initialize". Got 9 expected 8!'
      + expected - actual

      -Invalid number of parameters for "initialize". Got 9 expected 8!
      +ValidatorSet can't be 0
      
  

  6) Contract: StakingHbbft
       initialize()
         should fail if delegatorMinStake is zero:

      AssertionError: expected promise to be rejected with an error including 'DelegatorMinStake is 0' but got 'Invalid number of parameters for "initialize". Got 9 expected 8!'
      + expected - actual

      -Invalid number of parameters for "initialize". Got 9 expected 8!
      +DelegatorMinStake is 0
      
  

  7) Contract: StakingHbbft
       initialize()
         should fail if candidateMinStake is zero:

      AssertionError: expected promise to be rejected with an error including 'CandidateMinStake is 0' but got 'Invalid number of parameters for "initialize". Got 9 expected 8!'
      + expected - actual

      -Invalid number of parameters for "initialize". Got 9 expected 8!
      +CandidateMinStake is 0
      
  

  8) Contract: StakingHbbft
       initialize()
         should fail if already initialized:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Invalid number of parameters for "initialize". Got 9 expected 8!'
  

  9) Contract: StakingHbbft
       initialize()
         should fail if stakingEpochDuration is 0:

      AssertionError: expected promise to be rejected with an error including 'FixedEpochDuration is 0' but got 'Invalid number of parameters for "initialize". Got 9 expected 8!'
      + expected - actual

      -Invalid number of parameters for "initialize". Got 9 expected 8!
      +FixedEpochDuration is 0
      
  

  10) Contract: StakingHbbft
       initialize()
         should fail if stakingstakingEpochStartBlockWithdrawDisallowPeriod is 0:

      AssertionError: expected promise to be rejected with an error including 'WithdrawDisallowPeriod is 0' but got 'Invalid number of parameters for "initialize". Got 9 expected 8!'
      + expected - actual

      -Invalid number of parameters for "initialize". Got 9 expected 8!
      +WithdrawDisallowPeriod is 0
      
  

  11) Contract: StakingHbbft
       initialize()
         should fail if stakingWithdrawDisallowPeriod >= stakingEpochDuration:

      AssertionError: expected promise to be rejected with an error including 'FixedEpochDuration must be longer than withdrawDisallowPeriod' but got 'Invalid number of parameters for "initialize". Got 9 expected 8!'
      + expected - actual

      -Invalid number of parameters for "initialize". Got 9 expected 8!
      +FixedEpochDuration must be longer than withdrawDisallowPeriod
      
  

  12) Contract: StakingHbbft
       initialize()
         should fail if some staking address is 0:

      AssertionError: expected promise to be rejected with an error including 'InitialStakingAddresses can\'t be 0' but got 'Invalid number of parameters for "initialize". Got 9 expected 8!'
      + expected - actual

      -Invalid number of parameters for "initialize". Got 9 expected 8!
      +InitialStakingAddresses can't be 0
      
  

  13) Contract: StakingHbbft
       moveStake()
         "before each" hook for "should move entire stake":
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Invalid number of parameters for "initialize". Got 9 expected 8!'
  

  14) Contract: StakingHbbft
       stake()
         "before each" hook for "should be zero initially":
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Invalid number of parameters for "initialize". Got 9 expected 8!'
  

  15) Contract: StakingHbbft
       removePool()
         "before each" hook for "should remove a pool":
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Invalid number of parameters for "initialize". Got 9 expected 8!'
  

  16) Contract: StakingHbbft
       removeMyPool()
         "before each" hook for "should fail for zero gas price":
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Invalid number of parameters for "initialize". Got 9 expected 8!'
  

  17) Contract: StakingHbbft
       withdraw()
         "before each" hook for "should withdraw a stake":
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Invalid number of parameters for "initialize". Got 9 expected 8!'
  

  18) Contract: ValidatorSetHbbft
       newValidatorSet()
         "before each" hook for "can only be called by BlockReward contract":
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Invalid number of parameters for "initialize". Got 9 expected 8!'

**Comment by SurfingNerd** [comment]
checkin: 0688700b2f68e79f0b4a31d5fbee057996fe4ed8
  79 passing (8m)
  19 failing

  1) Contract: StakingHbbft
       claimReward()
         "before each" hook for "reward tries to be withdrawn before first stake":
     ReferenceError: stakingFixedEpochEndBlock is not defined
      at Context.beforeEach (test/StakingHbbft.js:377:36)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  2) Contract: StakingHbbft
       initialize()
         should initialize successfully:
     TypeError: Cannot read property 'call' of undefined
      at Context.it (test/StakingHbbft.js:1644:51)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  3) Contract: StakingHbbft
       initialize()
         should fail if stakingEpochDuration is 0:

      AssertionError: expected promise to be rejected with an error including 'FixedEpochDuration is 0' but got 'Returned error: VM Exception while processing transaction: revert FixedEpochDuration must be longer than withdrawDisallowPeriod -- Reason given: FixedEpochDuration must be longer than withdrawDisallowPeriod.'
      + expected - actual

      -Returned error: VM Exception while processing transaction: revert FixedEpochDuration must be longer than withdrawDisallowPeriod -- Reason given: FixedEpochDuration must be longer than withdrawDisallowPeriod.
      +FixedEpochDuration is 0
      
  

  4) Contract: StakingHbbft
       moveStake()
         should move entire stake:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Returned error: VM Exception while processing transaction: revert Withdraw: maxWithdrawAllowed exceeded -- Reason given: Withdraw: maxWithdrawAllowed exceeded.'
  

  5) Contract: StakingHbbft
       moveStake()
         should move part of the stake:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Returned error: VM Exception while processing transaction: revert Withdraw: maxWithdrawAllowed exceeded -- Reason given: Withdraw: maxWithdrawAllowed exceeded.'
  

  6) Contract: StakingHbbft
       moveStake()
         should move part of the stake:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Returned error: VM Exception while processing transaction: revert Withdraw: maxWithdrawAllowed exceeded -- Reason given: Withdraw: maxWithdrawAllowed exceeded.'
  

  7) Contract: StakingHbbft
       stake()
         should only success in the allowed staking window:
     AssertionError: expected promise to be rejected with an error including 'Stake: disallowed period' but it was fulfilled with { Object (tx, receipt, ...) }
  

  8) Contract: StakingHbbft
       withdraw()
         should withdraw a stake:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Returned error: VM Exception while processing transaction: revert Withdraw: maxWithdrawAllowed exceeded -- Reason given: Withdraw: maxWithdrawAllowed exceeded.'
  

  9) Contract: StakingHbbft
       withdraw()
         should fail if not initialized:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Returned error: VM Exception while processing transaction: revert Withdraw: maxWithdrawAllowed exceeded -- Reason given: Withdraw: maxWithdrawAllowed exceeded.'
  

  10) Contract: StakingHbbft
       withdraw()
         should fail for a zero pool address:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Returned error: VM Exception while processing transaction: revert Withdraw: maxWithdrawAllowed exceeded -- Reason given: Withdraw: maxWithdrawAllowed exceeded.'
  

  11) Contract: StakingHbbft
       withdraw()
         should fail for a zero amount:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Returned error: VM Exception while processing transaction: revert Withdraw: maxWithdrawAllowed exceeded -- Reason given: Withdraw: maxWithdrawAllowed exceeded.'
  

  12) Contract: StakingHbbft
       withdraw()
         shouldn't allow withdrawing from a banned pool:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Returned error: VM Exception while processing transaction: revert Withdraw: maxWithdrawAllowed exceeded -- Reason given: Withdraw: maxWithdrawAllowed exceeded.'
  

  13) Contract: StakingHbbft
       withdraw()
         shouldn't allow withdrawing during the stakingWithdrawDisallowPeriod:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Returned error: VM Exception while processing transaction: revert Withdraw: maxWithdrawAllowed exceeded -- Reason given: Withdraw: maxWithdrawAllowed exceeded.'
  

  14) Contract: StakingHbbft
       withdraw()
         should fail if non-zero residue is less than CANDIDATE_MIN_STAKE:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Returned error: VM Exception while processing transaction: revert Withdraw: maxWithdrawAllowed exceeded -- Reason given: Withdraw: maxWithdrawAllowed exceeded.'
  

  15) Contract: StakingHbbft
       withdraw()
         should fail if non-zero residue is less than DELEGATOR_MIN_STAKE:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Returned error: VM Exception while processing transaction: revert Withdraw: maxWithdrawAllowed exceeded -- Reason given: Withdraw: maxWithdrawAllowed exceeded.'
  

  16) Contract: StakingHbbft
       withdraw()
         should fail if withdraw more than staked:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Returned error: VM Exception while processing transaction: revert Withdraw: maxWithdrawAllowed exceeded -- Reason given: Withdraw: maxWithdrawAllowed exceeded.'
  

  17) Contract: StakingHbbft
       withdraw()
         should fail if withdraw already ordered amount:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Returned error: VM Exception while processing transaction: revert OrderWithdraw: not allowed -- Reason given: OrderWithdraw: not allowed.'
  

  18) Contract: StakingHbbft
       withdraw()
         should decrease likelihood:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Returned error: VM Exception while processing transaction: revert Withdraw: maxWithdrawAllowed exceeded -- Reason given: Withdraw: maxWithdrawAllowed exceeded.'
  

  19) Contract: ValidatorSetHbbft
       newValidatorSet()
         "before each" hook for "can only be called by BlockReward contract":
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Invalid number of parameters for "initialize". Got 9 expected 8!'
